chore: eslint test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,20 +1,13 @@
-#!/bin/bash
-branch="$(git rev-parse --abbrev-ref HEAD)"
-
-if [ "$branch" = "main" ]; then
-  echo "You can't commit directly to main branch"
-  exit 1
-fi
-if [ "$branch" = "stage" ]; then
-  echo "You can't commit directly to stage branch"
-  exit 1
-fi
-if [ "$branch" = "dev" ]; then
-  echo "You can't commit directly to dev branch"
-  exit 1
-fi
-
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+# Check branch name
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "main" ] || [ "$branch" = "stage" ] || [ "$branch" = "dev" ]; then
+  echo "You can't commit directly to $branch branch"
+  exit 1
+fi
+
+# Run lint-staged
 npx lint-staged
